Repository bentoml/OpenLLM, pull requests merged in 2023-09, with the labels that each got.

#302 docs: Update the readme
  README.md
Labels: documentation

#304 revert: disable compiled wheels for now
  .github/workflows/compile-pypi.yml
  .github/workflows/create-releases.yml
  .github/workflows/release-notes.yml
  .pre-commit-config.yaml
  changelog.d/304.change.md
Labels: 02 - Wheel Build, 03 - Standalone Build

#324 fix(serialisation): vllm ignore
  changelog.d/324.fix.md
  openllm-python/pyproject.toml
  openllm-python/src/openllm/_llm.py
  openllm-python/src/openllm/models/falcon/modeling_falcon.py
  openllm-python/src/openllm/models/llama/modeling_llama.py
  openllm-python/src/openllm/models/starcoder/modeling_starcoder.py
  openllm-python/src/openllm/serialisation/transformers/__init__.py
  openllm-python/src/openllm/serialisation/transformers/weights.py
  openllm-python/src/openllm/utils/dummy_pt_objects.py
  openllm-python/src/openllm/utils/dummy_vllm_objects.py
  tools/dependencies.py
Labels: 00 - EC2 Build, 02 - Wheel Build
